### ISSUE TITLE
Feature request: possibility to arm and disarm from HASS

### ISSUE THREAD

**Issue by paulius2k** [algirdasc/hass-secolink#2]
Ar teisingai supratau iš https://github.com/algirdasc/hass-secolink/issues/1, kad dabar nėra galimybės įjungti / išjungti signalizaciją per HASS?  Ar tai būtų padaroma? :)

**Comment by algirdasc** [comment]
Taip, nėra tokios galimybės, nes kiek žinau, raportai keliauja tik į vieną pusę, t.y. iš centralės į HA. Jei turi GSM modemą prie HA, galbūt būtų galima sužaisti SMS komandomis.
